apiVersion: build.dev/v1alpha1
kind: BuildStrategy
metadata:
  name: source-to-image
spec:
  buildSteps:
    - name: step-chown
      image: alpine:latest
      securityContext:
        runAsUser: 0
      command:
        - /bin/sh
      args:
        - -c
        - chown -v -R 1001:1001 /tekton/home/.docker /var/lib/containers/storage
      volumeMounts:
        - name: containers-storage
          mountPath: /var/lib/containers/storage
    - name: step-s2i-build
      image: quay.io/olemefer/source-to-image:latest
      securityContext:
        privileged: true
      workingDir: /workspace/source
      args:
        - build
        - .
        - "$(build.builderImage)"
        - "$(build.output.image)"
      volumeMounts:
        - name: containers-storage
          mountPath: /var/lib/containers/storage
    - name: step-s2i-push
      image: quay.io/olemefer/source-to-image:latest
      securityContext:
        privileged: true
      command:
        - /usr/bin/buildah
      args:
        - push
        - --tls-verify=false
        - $(build.output.image)
        - docker://$(build.output.image)
      volumeMounts:
        - name: containers-storage
          mountPath: /var/lib/containers/storage